[project]
name = "air-data-server"
version = "0.1.0"
description = ""
authors = [
    {name = "Eemil Sinkko",email = "eemil.sinkko@helsinki.fi"},
    {name = "Juhani Kataja",email = "juhani.kataja@helsinki.fi"},
    {name = "Jaakko Airikkala",email = "jaakko.airikkala@helsinki.fi"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "paho-mqtt (>=2.1.0,<3.0.0)",
    "invoke (>=3.0.3,<4.0.0)",
    "nuitka (>=4.2.1,<5.0.0)",
    "flask (>=3.1.3,<4.0.0)",
    "gunicorn (>=26.2.0,<27.0.0)",
    "zstandard (>=0.25.0,<0.26.0)"
]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
